configure: show the list of missing packages

diff --git a/scripts/configure b/scripts/configure
--- a/scripts/configure
+++ b/scripts/configure
@@ -10,7 +10,12 @@ echo '# packages: $PKGS'
 readonly PKGS="$@"
 if [ ! -z "$PKGS" ] ; then
   if ! pkg-config --exists "$PKGS" ; then
-    echo "Some packages were not found" >&2
+    echo "Some packages were not found:" >&2
+    for pkg in $PKGS ; do
+      if ! pkg-config --exists "$pkg" ; then
+        echo "* $pkg"
+      fi
+    done
     exit 1
   fi
 
