Use a trick to abort the build early when some deps aren't found

diff --git a/scripts/pkg-config b/scripts/pkg-config
--- a/scripts/pkg-config
+++ b/scripts/pkg-config
@@ -4,4 +4,7 @@ set -euo pipefail
 export EXTRA=${EXTRA-$PWD/sysroot}
 export PKG_CONFIG_PATH=$EXTRA/lib/pkgconfig:${PKG_CONFIG_PATH-}
 
-pkg-config "$@"
+if ! pkg-config "$@" ; then
+  echo "--abort-the-build-because-some-libs-were-not-found"
+  exit 1
+fi
